name: destrostudios
services:
  db:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    volumes:
      - /home/destroflyer/destrostudios/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 3s
      retries: 0
    restart: always
  db-ui:
    image: destrostudios/phpmyadmin
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "8081:443"
    restart: always
  app:
    build:
      dockerfile: app.Dockerfile
    environment:
      AUTH_PRIVATE_KEY: $AUTH_PRIVATE_KEY
      AUTH_PRIVATE_KEY_PASSPHRASE: $AUTH_PRIVATE_KEY_PASSPHRASE
      SERVER_SSL_KEY-STORE-PASSWORD: $KEYSTORE_PASSWORD
      SPRING_DATASOURCE_PASSWORD: $DB_ROOT_PASSWORD
      SPRING_MAIL_PASSWORD: $SUPPORT_EMAIL_PASSWORD
    volumes:
      - /var/www/destrostudios/apps:/home/apps:ro
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: always